### ISSUE TITLE
Question: Way to limit the number of parallel running Jobs

### ISSUE THREAD

**Issue by Nplu5** [quarkiverse/quarkus-jberet#189]
I develop a quarkus application that gathers data from users and they can request a report of the data. I want to use JBeret for the report generation but additionally I want to limit the amount of parallel Jobs as I do not want to interfere with the gatheriing of data and ensure full functionality. 

What would be the way to achieve this behaviour with JBeret/this extension? 

If it requires code changes I would be happy to contribute given some guidance.

**Comment by radcortez** [comment]
The JBeret Extension delegates the execution to Quarkus Thread Pool, and it is allowed to use the total capacity of the pool. 

We can certainly expose configuration to limit the number of threads that it can use.

**Comment by Nplu5** [comment]
That sound great. I can create a PR if you point me into the starting direction.

**Comment by radcortez** [comment]
Sure. Check https://github.com/quarkiverse/quarkus-jberet/blob/87f8d07793a0290534d84909c558f9e91ef0a711/core/runtime/src/main/java/io/quarkiverse/jberet/runtime/QuarkusJobExecutor.java#L10-L22
