### ISSUE TITLE
Starting job defined using Job Definition in Java and @Named bean

### ISSUE THREAD

**Issue by gquintana** [quarkiverse/quarkus-jberet#227]
Given a job defined using the Java DSL (instead of the XML DSL):
```java
  @Produces
  @Named("myJob")
  public Job job() {
    return new JobBuilder("myJob")....build();
  }
```
I can launch it using `public long start(final Job jobDefined, final Properties jobParameters)` method, but it requires me to inject or resolve the Job bean instance.
I would like the `public long start(String jobXMLName, Properties jobParameters, String user)` to use the jobXMLName to first look for the Job in XML config and then look for the Job in CDI managed beans with `@Named` and type `Job`. 
To avoid breaking the JBatch start method contract, alternatives could be 
* to add a `Job getJob(String jobName)` in `QuarkusJobOperator`
* to be able to inject all named Jobs in a Map:  `@Inject @All Map<String, Job> namedJobs`

**Comment by radcortez** [comment]
I won't oppose to also look Jobs by their CDI name if an XML name cannot be found.

> * to be able to inject all named Jobs in a Map:  `@Inject @All Map<String, Job> namedJobs`

This is already possible with plain CDI. Try:

```java
@Inject
Instance<Job> jobs
```

Then you just iterate them to search for a given name or you can even convert them to a Map.

**Comment by gquintana** [comment]
An open question is what name should be used when CDI and JBatch names are different
```
  @Produces
  @Named("foo")
  public Job job() {
    return new JobBuilder("bar")....build();
  }
 ```

**Comment by radcortez** [comment]
In this case, CDI does not know about the internal name assigned in the Job, it would either use the name from the `@Named` annotation or use the default CDI generated name, but never the builder name.
