### ISSUE TITLE
Start a job defined in java (programatic) using Rest API

### ISSUE THREAD

**Issue by ricardojlrufino** [quarkiverse/quarkus-jberet#245]
Hi, i like to start using rest api (jbarret-rest), but this not woks for Programatic jobs 

```bash
curl -X 'POST' \
  'http://localhost:8080/jobs/programaticJob/start' \
  -H 'Content-Type: application/json' \
  -d '{
        "myTestCase" : "SUCCESS"
  }'
```

`16:45:19 WARN  [or.jb.rest-api] (executor-thread-1)  JBERET070500: Exception occurred when accessing JBeret Rest API:: jakarta.batch.operations.NoSuchJobException: Job with xml name programaticJob was not found`

**My class**

```java
import org.jberet.job.model.Job;
import org.jberet.job.model.JobBuilder;
import org.jberet.job.model.StepBuilder;

import jakarta.enterprise.context.Dependent;
import jakarta.enterprise.inject.Produces;
import jakarta.inject.Named;

@Dependent
public class ProgramaticJob {

        public static final String JOB_NAME = "programaticJob";

        @Produces
        @Named(JOB_NAME)
        public Job create() {

                // Mais exemplos:
                // https://jberet.gitbooks.io/jberet-user-guide/content/programmatic_job_definition_with_java/

                String batchlet1Name = "demoJobStep";

                return new JobBuilder(JOB_NAME)
                                .restartable(false)
                                .property("myTestCase", "SUCCESS")

                                .step(new StepBuilder("step-01")
                                                .batchlet(batchlet1Name, new String[] { "myTestCase", "SUCCESS" })
                                                .nextOn("*").to("step-02")
                                                .build())

                                .step(new StepBuilder("step-02")
                                                .batchlet(batchlet1Name, new String[] { "myTestCase", "DELAY" })
                                                .stopOn("STOP").restartFrom("step-01").exitStatus()
                                                .endOn("END").exitStatus()
                                                .failOn("FAIL").exitStatus()
                                                .build())

                                .build();
        }

}

```

**Comment by radcortez** [comment]
I believe that JBeret does not support Job creation using CDI. At least nothing in the docs indicates that: https://jberet.gitbooks.io/jberet-user-guide/content/programmatic_job_definition_with_java/. We can certainly add such capability.

**Comment by ricardojlrufino** [comment]
I think that is easy to add this support in quarkus side.

Only add
```java
Job programaticJob = CDI.current()
                    .select(Job.class, NamedLiteral.of(jobName))
                    .get();
                    
long executionId = jobOperator.start(programaticJob, jobParameters);
```

On class
https://github.com/quarkiverse/quarkus-jberet/blob/main/core/runtime/src/main/java/io/quarkiverse/jberet/runtime/QuarkusJobOperator.java#L65

**Comment by radcortez** [comment]
I believe it would be better to add them with the rest of the XML jobs here:
https://github.com/quarkiverse/quarkus-jberet/blob/0c96560192c20c605a9ef63f0473f1d7511fc53f/core/runtime/src/main/java/io/quarkiverse/jberet/runtime/JBeretRecorder.java#L36-L60

Would you like to try sending a PR? :) Thanks!

**Comment by ricardojlrufino** [comment]
I'm trying to validate if JBeret can replace Spring Batch...

I'm still testing and I'm having difficulty using JBeret in some scenarios...

For example, I was unable to stop a JOB. After trying for a long time, I discovered that it is related to activating jpa for batches, somehow this interferes and it is not possible to stop the JOB.

**Comment by ricardojlrufino** [comment]
I'm sending a small example highlighting this problem.
Test by enabling/disabling the datasource, and you will see that the stop does not work if it is enabled.

After calling rest API : `/jobexecutions/151/stop`, the job keep kurring if JPARespository is enabled for job
![image](https://github.com/quarkiverse/quarkus-jberet/assets/515675/701132fc-428a-459b-abd4-d73d17f553fa)

I also did a small Junit test to check: `mvn test -Dtest=ChunkStopTest`
[issues-sample.zip](https://github.com/quarkiverse/quarkus-jberet/files/12668065/issues-sample.zip)

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
It seems that the jpa repository, queries the database to retrieve the execution instead of reusing the cached one that the jobcontext uses to signal state changes.

This needs to be fixed at https://github.com/jberet/jberet-jpa-repository.

I recommend changing to the `jdbc` repository type, which works as expected.
