### ISSUE TITLE
Is it possible to resove JBeret "quarkified" artifacts with Universe BOM only?

### ISSUE THREAD

**Issue by x80486** [quarkiverse/quarkus-jberet#251]
I usually have to declare `implementation(enforcedPlatform("io.quarkus:quarkus-universe-bom:3.X.Y"))` only in `Gradle` in order to resolve all `Quarkus` dependencies released with the `Quarkus` version in question.

This doesn't work with `io.quarkiverse.jberet:quarkus-jberet`.

Would it be possible to make the JBeret "quarkified" releases to be resolved in such way?

**Comment by radcortez** [comment]
Yes, JBeret is not part of the Quarkus platform BOM. so you need to add the dependency separately.

I'm not sure if JBeret should be part of it, but let me discuss it with the rest of the team.

**Comment by radcortez** [comment]
Generated a BOM; now this one has to be included in https://github.com/quarkusio/quarkus-platform
