### ISSUE TITLE
scheduler fires on quarkus startup execution of job

### ISSUE THREAD

**Issue by michaelsonnleitner** [quarkiverse/quarkus-jberet#254]
I configured a cron expressoin for my job in application.properties like:

`quarkus.jberet.job."jobname".cron=0 0 19 ? * *`

Expected:
This cron should start the job every day at 7pm.

Current situation:
Job is started after Quarkus is startet AND every day at 7pm.

Why is the job started when quarkus is launched?

**Comment by wrssmi** [comment]
cool. thanks could you also apply it to the 1 version - would be really nice - i am usong quarkus 2.16
