### ISSUE TITLE
Compilation error when there is a groovy script job

### ISSUE THREAD

**Issue by falcantaracano** [quarkiverse/quarkus-jberet#28]
Hi,
 I get the following compilation error when I have defined a Job with an external groovy script the step.

Job definition: helloGroovyJob.xml
<?xml version="1.0" encoding="UTF-8"?>
<job id="helloGroovyJob" version="1.0" xmlns="http://xmlns.jcp.org/xml/ns/javaee">
   	<step id="helloGroovyStep">
    	<batchlet>
    		<script src="groovy/HelloGroovyBachlet.groovy" />
    	</batchlet>
   	</step> 
</job>

Compilation error after execution of mvnw package
D:\desa\eclipse-dev\quarkus-picocli-example>mvnw package
[INFO] Scanning for projects...
[INFO]
[INFO] --------------< quarkus-examples:quarkus-picocli-example >--------------
[INFO] Building quarkus-picocli-example 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.12.0.Final:generate-code (default) @ quarkus-picocli-example ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quarkus-picocli-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ quarkus-picocli-example ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO]
[INFO] --- quarkus-maven-plugin:1.12.0.Final:generate-code-tests (default) @ quarkus-picocli-example ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ quarkus-picocli-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\desa\eclipse-dev\quarkus-picocli-example\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ quarkus-picocli-example ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ quarkus-picocli-example ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ quarkus-picocli-example ---
[INFO] Building jar: D:\desa\eclipse-dev\quarkus-picocli-example\target\quarkus-picocli-example-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- quarkus-maven-plugin:1.12.0.Final:build (default) @ quarkus-picocli-example ---
[INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
[INFO] [org.jberet] JBERET000030: Resolved job file:/D:/desa/eclipse-dev/quarkus-picocli-example/target/classes/META-INF/batch-jobs/helloGroovyJob.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.478 s
[INFO] Finished at: 2021-03-03T12:31:29+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.12.0.Final:build (default) on project quarkus-picocli-example: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: java.lang.RuntimeException: Failed to record call to method public void io.quarkiverse.jberet.runtime.JBeretRecorder.registerJobs(java.util.List)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:452)
[ERROR]         at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:437)
[ERROR]         at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:170)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Cannot serialise field 'type' on object 'org.jberet.job.model.Script@3b6a1f53' as the property is read only
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1371)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:956)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:548)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1114)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:956)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:548)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:447)
[ERROR]         ... 12 more
[ERROR] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Cannot serialise field 'type' on object 'org.jberet.job.model.Script@3b6a1f53' as the property is read only
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1371)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:956)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:548)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1114)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:956)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:548)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1336)
[ERROR]         ... 18 more
[ERROR] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Cannot serialise field 'type' on object 'org.jberet.job.model.Script@3b6a1f53' as the property is read only
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1371)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:956)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:548)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1336)
[ERROR]         ... 24 more
[ERROR] Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Cannot serialise field 'type' on object 'org.jberet.job.model.Script@3b6a1f53' as the property is read only
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1301)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:956)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:548)
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1336)
[ERROR]         ... 27 more
[ERROR] Caused by: java.lang.RuntimeException: Cannot serialise field 'type' on object 'org.jberet.job.model.Script@3b6a1f53' as the property is read only
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1292)
[ERROR]         ... 30 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Environment:
JDK Version  AdoptOpenJDK  11.0.8.10-hotspot
IDE: Eclipse 2020-12
maven: 3.6.3
OS: Windows 10 Pro

I have tried also putting type="groovy" in the script reference, but I get the same error.

Sinceraly
Fernando

**Comment by falcantaracano** [comment]
Sorry, I don´t copy&paste correctly. The correct job definition is:
<?xml version="1.0" encoding="UTF-8"?>
<job id="helloGroovyJob" version="1.0" xmlns="http://xmlns.jcp.org/xml/ns/javaee">

   	<step id="helloGroovyStep">
    	<batchlet id="helloGroovyBachlet">
    		<script src="groovy/HelloGroovyBachlet.groovy" />
    	</batchlet>
   	</step>
    
</job>

**Comment by radcortez** [comment]
Most likely, I didn't add support for JBeret scripts. 

Would you mind sending me a reproducer so I can test myself? Thanks!

**Comment by falcantaracano** [comment]
Hi Roberto,

This is the my basic example project [quarkus-jberet-scripts.zip](https://github.com/quarkiverse/quarkus-jberet/files/6085739/quarkus-jberet-scripts.zip) for this use case. I have added a test case, which it launch JBeret groovy script Job. The example can execute from command line following the instructions in README.md. In these case, the BatchGroovyCmd class launch the Jberet groovy script job.

The Jberet groovy script job reference to an external groovy script. This script is in `src/main/resources/groovy` directory. You can also put the `type = "groovy"` attribute in `<script type = "groovy" src="groovy/HelloGroovyBachlet.groovy" />` in `helloGroovyJob.xml` job definition file.

You can find more JBeret scripts job definitions in the following URL: [test-apps/scripting](https://github.com/jberet/jsr352/tree/master/test-apps/scripting)

Feel free to ask what you need. Sinceraly

Fernando

**Comment by radcortez** [comment]
Thanks! I'll have a look.

**Comment by radcortez** [comment]
@falcantaracano I've added a fix to support JBeret `Script`, but we need some changes on the JBeret side as well.

**Comment by falcantaracano** [comment]
Thanks. 
Do you know when Jberet changes will be released?

**Comment by radcortez** [comment]
@falcantaracano this should work now in 0.0.5. Thanks!
