### ISSUE TITLE
JBERET000651: The requested permits (2) is greater than the maximum number of permits (1) allowed in the thread pool.

### ISSUE THREAD

**Issue by cedricwalter** [quarkiverse/quarkus-jberet#30]
We got this error in openshift 4.0 with quarkus 1.11.0-Final and latest quarkus-jberet

```
org.jboss.threads.JBossThread.run(JBossThread.java:501)
: java.lang.IllegalStateException: JBERET000651: The requested permits (2) is greater than the maximum number of permits (1) allowed in the thread pool.
```

Is this something we can solve in application.properties? or in openshift environment?

**Comment by radcortez** [comment]
Thanks for using the JBeret Extension.

Do you know if this only happens in OpenShift? Are you able to provide me with a reproducer? Thanks!

**Comment by cedricwalter** [comment]
We found it the quota imposed by openshift for the pod was way too low, was 400m setting it to 2000m or 2 cores fixes the issues!

           resources:
                requests:
                  cpu: 50m
                  memory: 50Mi
                limits:
                  cpu: 2000m
                  memory: 500Mi

**Comment by radcortez** [comment]
Great!
