### ISSUE TITLE
Support ServiceLoader injection for JobXmlResolver in JBeretProcessor

### ISSUE THREAD

**Issue by franzmathauser** [quarkiverse/quarkus-jberet#311]
Hi everyone,

at the moment it is not possible to replace the usage of MetaInfBatchJobsJobXmlResolver with a custom implementation within the JBeretProcessor because it is directly instantiated within the class.

Codepointer of relevance:
https://github.com/quarkiverse/quarkus-jberet/blob/main/core/deployment/src/main/java/io/quarkiverse/jberet/deployment/JBeretProcessor.java#L242

Would be nice to register a custom implementation of the JobXmlResolver SPI, since the read xml files are cached after application startup.

**Comment by franzmathauser** [comment]
Hi @radcortez, 
thanks for taking time to answer my request. Yes, that would be totally fine at startup time. We want to use a custom JobXmlResolver to enrich jobs and steps with generic listeners, instead of having that as part of the job xml configuration, which would make it less readable. Would be great to use the service loader to have our version of the xml resolver in place.

**Comment by radcortez** [comment]
We want to keep it build time; I was asking to try to understand the requirement. 

If that is okay, we can change the build time processor to use a `ServiceLoader`om `JobXmlResolver` as a standalone JBeret.

**Comment by franzmathauser** [comment]
Sounds like a plan. 👍 Thank you

**Comment by jenswet** [comment]
Hi @radcortez,

do you already know when the next release will happen? I am interested in this feature as well.

Thanks,
Jens

**Comment by radcortez** [comment]
I'll release the new version with Quarkus 3.14.
