### ISSUE TITLE
Cannot restart a failed job on quarkus-app restart (jdbc repository)

### ISSUE THREAD

**Issue by rodrahul** [quarkiverse/quarkus-jberet#36]
- Started a quarkus app (_mvnw quarkus:dev_) with jberet jdbc-repository.
- Submitted a chunk based job, which results in failure.
- Stopped quarkus app
- Start quarkus app, and restar the job using jberet-rest endpoint _(/lms/jobexecutions/{jobExecutionId}/restart)_
- We get an java.lang.UnsupportedOperationException exception 
snippet of stack trace 
`at io.quarkiverse.jberet.runtime.QuarkusBatchEnvironment.getJobXmlResolver(QuarkusBatchEnvironment.java:69)
	at org.jberet.operations.AbstractJobOperator.restartFailedOrStopped(AbstractJobOperator.java:402)
	at org.jberet.operations.AbstractJobOperator.restart(AbstractJobOperator.java:253)
	at org.jberet.operations.AbstractJobOperator.restart(AbstractJobOperator.java:225)
	at io.quarkiverse.jberet.runtime.QuarkusJobOperator.restart(QuarkusJobOperator.java:81)
	at org.jberet.operations.DelegatingJobOperator.restart(DelegatingJobOperator.java:73)
	at org.jberet.rest.service.JobService.restart(JobService.java:166)
	at org.jberet.rest.resource.JobExecutionResource.restart(JobExecutionResource.java:150)`

This happens because we cannot find a Job in _AbstractJobOperator_ at
 https://github.com/jberet/jsr352/blob/738f1805a872ec3a2618c1cd2b1726b6afe8c458/jberet-core/src/main/java/org/jberet/operations/AbstractJobOperator.java#L387
which triggers a _batchEnvironment.getJobXmlResolver()_
at https://github.com/jberet/jsr352/blob/738f1805a872ec3a2618c1cd2b1726b6afe8c458/jberet-core/src/main/java/org/jberet/operations/AbstractJobOperator.java#L402

If we restart the job without restarting our quarkus-app, we don't face the above issue

**Comment by rodrahul** [comment]
Possible fix can be to override the restart method in _QuarkusJobOperator_

`@Override
    public long restart(long executionId, Properties restartParameters) throws JobExecutionAlreadyCompleteException,
            NoSuchJobExecutionException, JobExecutionNotMostRecentException, JobRestartException, JobSecurityException {

        JobExecutionImpl originalToRestart = (JobExecutionImpl) getJobRepository().getJobExecution(executionId);
        JobInstanceImpl jobInstance = originalToRestart.getJobInstance();
        Job jobDefinition = jobInstance.getUnsubstitutedJob();
        if (jobDefinition == null) {
            System.out.println("JOB IS NULL");
            jobDefinition = jobs.get("assignItemToUsers");
            jobInstance.setUnsubstitutedJob(jobDefinition);
        }

        if (jobDefinition != null) {
            return super.restart(executionId, restartParameters);
        } else {
            throw new NoSuchJobException("Job with executionId " + executionId + " was not found");
        }
    }`

**Comment by radcortez** [comment]
Let me have a look.

**Comment by radcortez** [comment]
@rodrahul Thanks for the suggestions I've made some adjustments. Can you please check if #38 works for you?

**Comment by rodrahul** [comment]
Sure, let me check it out

**Comment by rodrahul** [comment]
Works like a charm. Thanks for quick turn around :)

**Comment by radcortez** [comment]
Thanks! I'll do a release either today or tomorrow with the fix.
