### ISSUE TITLE
Support named jberet repository definition in application.properties 

### ISSUE THREAD

**Issue by rodrahul** [quarkiverse/quarkus-jberet#45]
I've set my persistence unit as a named persistence unit in application.properties (This can also be if using multiple persistence units)

e.g.
```
quarkus.datasource."mydb".db-kind=mariadb
quarkus.datasource."mydb".jdbc.url=${DATABASE_URL:jdbc:mariadb://127.0.0.1:3306/test}
quarkus.datasource."mydb".username=xxxxx
quarkus.datasource."mydb".password=xxxxx

quarkus.jberet.repository.type=JDBC
```

The above configuration gives the following error 
```
2021-04-02 14:43:22,299 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.jberet.deployment.JBeretProcessor#init threw an exception: io.quarkus.deployment.configuration.ConfigurationError: TODO

at io.quarkiverse.jberet.deployment.JBeretProcessor.validateRepository(JBeretProcessor.java:301)
at io.quarkiverse.jberet.deployment.JBeretProcessor.init(JBeretProcessor.java:176)
```

**Environment** 
Quarkus: 1.12.2.Final
jberet: 0.0.5

**Workaround** 
I'm working around this by adding a default persistence unit to my properties file
```
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:mariadb://127.0.0.1:3306/test}
quarkus.datasource.username=xxxxx
quarkus.datasource.password=xxxxx
```

**Expected Behavior**
We should be able to define the jberet repository if using a named persistence unit or in case of multiple persistence units
e.g.

```
quarkus.jberet.repository.name=mydb
quarkus.jberet.repository.type=JDBC
```

**Comment by radcortez** [comment]
Thanks @rodrahul. I'll have a look.

**Comment by radcortez** [comment]
Hi @rodrahul. Actually this is already supported with `quarkus.jberet.repository.jdbc.datasource`. It was not documented. Please check #46.

**Comment by rodrahul** [comment]
I did try out with `quarkus.jberet.repository.jdbc.datasource=mydb` and works perfectly and simplifies my properties file a lot.

The TODO exception threw me off when I was debugging initially. 
With proper documentation this should not be an issue anymore.

Thank you.

**Comment by radcortez** [comment]
Yes. It validates that the property datasource name is valid one, by matching the datasource definitions, but I guess I forgot to  set the proper error message when I was implementing it. The PR will fix that.
